columnSuffix: null
handle: body
instructions: null
name: Body
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: 4a6bdd90-6129-4622-bf45-24682ce34d48 # Simple
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: true
  purifierConfig: null
  purifyHtml: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
