columnSuffix: null
handle: callToAction
instructions: null
name: 'Call to Action'
searchable: false
settings:
  createButtonLabel: null
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - efce25fb-7bd4-49cc-8f17-a84b348cf349 # Link
  includeTableView: false
  maxEntries: 1
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
