columnSuffix: null
handle: entry
instructions: null
name: Entry
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  maintainHierarchy: false
  maxRelations: 1
  minRelations: 0
  selectionLabel: null
  showCardsInGrid: false
  showSiteMenu: true
  sources:
    - 'section:c1f9043c-a9fe-4828-8b12-e36d12842d7e' # Page
    - 'section:e20465eb-96b7-4f76-9f57-e12f30c984cf' # Post
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
