columnSuffix: null
handle: featuredPost
instructions: null
name: 'Featured Post'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  selectionLabel: 'Add a post'
  showCardsInGrid: false
  showSiteMenu: false
  sources:
    - 'section:e20465eb-96b7-4f76-9f57-e12f30c984cf' # Post
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
