columnSuffix: null
handle: headerLevelStyle
instructions: null
name: 'Header Level Style'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - H0
        -
          - value
          - h0
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - H1
        -
          - value
          - h1
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - H2
        -
          - value
          - h2
        -
          - default
          - '1'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
