columnSuffix: null
handle: headerLevel
instructions: null
name: 'Header Level Element'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - H1
        -
          - value
          - h1
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - H2
        -
          - value
          - h2
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
