columnSuffix: null
handle: links
instructions: null
name: Links
searchable: false
settings:
  createButtonLabel: 'New Link'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - efce25fb-7bd4-49cc-8f17-a84b348cf349 # Link
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
