columnSuffix: null
handle: linkType
instructions: null
name: 'Link Type'
searchable: true
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Custom
        -
          - value
          - custom
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Entry
        -
          - value
          - entry
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
