columnSuffix: null
handle: mediaItems
instructions: null
name: 'Media Items'
searchable: false
settings:
  createButtonLabel: 'New media item'
  entryTypes:
    - f0d9e50f-3e81-47db-97c3-15d59a8a7b37 # Media
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
