columnSuffix: null
handle: mediaItem
instructions: null
name: 'Media Item'
searchable: false
settings:
  createButtonLabel: 'New media item'
  defaultIndexViewMode: cards
  entryTypes:
    - f0d9e50f-3e81-47db-97c3-15d59a8a7b37 # Media
  includeTableView: false
  maxEntries: 1
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
