columnSuffix: null
handle: menus
instructions: null
name: Menus
searchable: false
settings:
  createButtonLabel: 'New menu'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 1ff5212e-5424-4f4e-a34c-22ccf90fdff5 # Menu with Title
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
