columnSuffix: null
handle: pageSections
instructions: null
name: 'Page Sections'
searchable: true
settings:
  createButtonLabel: 'New section'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 388d380e-2738-48e8-b422-4ba2d7aaf746 # Hero
    -
      __assoc__:
        -
          - uid
          - 952796bd-d102-4fcb-ab22-f9e776446004 # Satellite Intro
    -
      __assoc__:
        -
          - uid
          - 369e4ada-b4b2-4b43-8ce0-0fd6a2f8a59e # Animation Slides
    -
      __assoc__:
        -
          - uid
          - a233aa63-0d9d-48d3-a11c-011ad884113f # Satellite Explorer
    -
      __assoc__:
        -
          - uid
          - f0683f0c-7adb-40a0-bd6c-3f8ecdfdeb86 # Conclusion
    -
      __assoc__:
        -
          - uid
          - 62813de0-4c17-45dc-85d0-3ad618fbac34 # Rich Text
    -
      __assoc__:
        -
          - uid
          - d8122882-d2f2-4aa0-b2dd-e7159cbb5e67 # Post Index
    -
      __assoc__:
        -
          - uid
          - 5dec678a-093e-432b-abd7-d39122a02195 # Post Previews
    -
      __assoc__:
        -
          - uid
          - c95691a0-b3a2-44cb-bcf6-03d744bf038a # Media Items
    -
      __assoc__:
        -
          - uid
          - 21b17955-d751-4222-af9d-db6b6d7d0a00 # Progress
    -
      __assoc__:
        -
          - uid
          - cd720f0e-9aa8-440b-9df1-68d2c5f16d6c # About
    -
      __assoc__:
        -
          - uid
          - 74aa3075-6b50-4195-bc56-76a73f409d11 # Partners
    -
      __assoc__:
        -
          - uid
          - 3b8c826c-5b3e-49eb-a802-ee27369fb357 # Accordion
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
