columnSuffix: null
handle: postSections
instructions: null
name: 'Post Sections'
searchable: false
settings:
  createButtonLabel: 'New section'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - bb4c4dc7-c063-4bac-be45-47d37130a515 # Post Rich Text
    -
      __assoc__:
        -
          - uid
          - 0005823c-523f-4a5a-a6a3-eed6059e7483 # Post Media
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
