columnSuffix: null
handle: postCategories
instructions: null
name: 'Post Categories'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  maintainHierarchy: false
  maxRelations: 1
  minRelations: 1
  selectionLabel: null
  showCardsInGrid: false
  showSiteMenu: false
  source: 'group:4fdb97ac-06c8-4dc0-abf3-5b73cf2853f7' # Post Categories
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Categories
