columnSuffix: null
handle: scale
instructions: null
name: Scale
searchable: false
settings:
  defaultValue: 100
  max: 200
  min: 0
  step: 1
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Range
