columnSuffix: null
handle: stepStatus
instructions: null
name: Status
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Complete
        -
          - value
          - complete
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - In-Progress
        -
          - value
          - inProgress
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Upcoming
        -
          - value
          - upcoming
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
