columnSuffix: null
handle: style
instructions: null
name: Style
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Inline
        -
          - value
          - inline
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Wide
        -
          - value
          - wide
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Narrow
        -
          - value
          - narrow
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
