defaultPlacement: end
enableVersioning: true
entryTypes:
  - 504a522f-fe0a-479a-81c4-098d2413233c # Page
handle: page
maxAuthors: 1
name: Page
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  04df0f5f-b9d5-4dda-b9a8-bcccda506022: # Pathstream
    enabledByDefault: true
    hasUrls: true
    template: _page.twig
    uriFormat: '{slug}'
type: channel
