defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: af1b9965-7196-45cb-9406-acbebe4c622e # Post
handle: post
maxAuthors: 1
name: Post
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  04df0f5f-b9d5-4dda-b9a8-bcccda506022: # Pathstream
    enabledByDefault: true
    hasUrls: true
    template: _post.twig
    uriFormat: 'updates/{slug}'
type: channel
