fieldLayouts:
  a3ca9ae2-ecca-40f4-a3a4-8570e6bebfac:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-13T21:14:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 1c648a4a-9d05-4354-be01-759a26e1b7a0 # HTML
            handle: scripts
            includeInCards: false
            instructions: null
            label: Scripts
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9a0d2645-e968-4f40-9693-80649662ca94
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 16776f4a-cf80-44ef-ac2e-4643d7311e1c
        userCondition: null
handle: scripts
name: Scripts
sortOrder: 5
