css: ".ck.ck-content div {\r\n  border: 1px solid #ccc;\r\n  padding: 6px;\r\n  border-radius: 4px;\r\n  margin-bottom: 10px;\r\n}\r\n\r\n.ck.ck-content div::before {\r\n  content: '<div>';\r\n  font-family: 'Courier New', Courier, monospace;\r\n  font-size: 12px;\r\n}\r\n\r\n.ck.ck-editor__editable span[data-ck-unsafe-element=\"script\"] {\r\n  border: 1px solid #ccc;\r\n  padding: 6px;\r\n  border-radius: 4px;\r\n  margin-bottom: 10px;\r\n  display: block !important;\r\n}\r\n\r\n.ck.ck-editor__editable span[data-ck-unsafe-element=\"script\"]::before {\r\n  content: '<script> (view source)';\r\n  font-family: 'Courier New', Courier, monospace;\r\n  font-size: 12px;\r\n}"
headingLevels:
  - 2
  - 3
js: "return {\r\n  heading: {\r\n    options: [\r\n      {\r\n        model: 'paragraph',\r\n        title: 'Paragraph',\r\n      },\r\n      {\r\n        model: 'heading2',\r\n        view: 'h2',\r\n        title: 'Heading 2',\r\n      },\r\n      {\r\n        model: 'heading3',\r\n        view: 'h3',\r\n        title: 'Heading 3',\r\n      },\r\n    ],\r\n  },\r\n  htmlSupport: {\r\n    allow: [\r\n      {\r\n            name: /.*/,\r\n            attributes: true,\r\n            classes: true,\r\n            styles: true\r\n      },\r\n    ],\r\n  },\r\n  fontSize: {\r\n    options: [\r\n      'normal',\r\n      'small'\r\n    ],\r\n  },\r\n}"
name: Simple
toolbar:
  - heading
  - '|'
  - bold
  - italic
  - blockQuote
  - fontSize
  - bulletedList
  - numberedList
  - subscript
  - superscript
  - link
  - insertImage
  - insertTable
  - sourceEditing
