color: null
fieldLayouts:
  946b76f1-3c3d-4b78-a97f-7ab63f0a5ed9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-06T23:24:15+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9f0b5e58-34b1-4bc8-b7b8-e58d99b93231
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-06T23:27:28+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: aac3e44d-b810-42c7-be08-8c6a19a3340a # Media Item
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9001ed71-24be-445e-ab9f-4588f818def4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-06T23:27:28+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: d9eb71bd-20b2-465c-bc56-b79f2893bd37
            userCondition: null
          -
            dateAdded: '2025-05-06T23:27:28+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0fe347cf-5e7b-4446-a9e1-359f64551463 # Text
            handle: primaryBodyHeadline
            includeInCards: false
            instructions: null
            label: 'Primary Body Headline'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a2084488-e221-454a-8805-586b1ea51cd8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-06T23:27:28+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c975e4b8-725b-40cf-8289-e0758ed7d08a # Body
            handle: primaryBody
            includeInCards: false
            instructions: null
            label: 'Primary Body'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b7773583-de75-4c03-a0bf-d09fd863b052
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-06T23:27:28+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 61753dc9-47b7-4b4c-a430-aa72cb5b99ce
            userCondition: null
          -
            dateAdded: '2025-05-06T23:27:28+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0fe347cf-5e7b-4446-a9e1-359f64551463 # Text
            handle: secondaryBodyHeadline
            includeInCards: false
            instructions: null
            label: 'Secondary Body Headline'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ec8409db-10f5-4ae6-8148-b7a93708c58d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-06T23:27:28+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c975e4b8-725b-40cf-8289-e0758ed7d08a # Body
            handle: secondaryBody
            includeInCards: false
            instructions: null
            label: 'Secondary Body'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2695b8bf-765c-4ea1-9507-1925680b82fa
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-06T23:27:28+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e3c44a40-6b4f-492f-945f-b71ab515f2cc # Links
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ace6809c-d8ea-492b-b40f-9aadf21aea40
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6fee2b4a-3803-476d-9cff-2a3ecd2f9edf
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-01T16:56:40+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6ed3184f-7a68-4bb3-b991-e86a3a3fac25 # Section ID
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b8c06c36-0e47-4c14-86e3-5b06e9d04467
            userCondition: null
            warning: null
            width: 100
        name: Config
        uid: b564be39-776c-4370-a544-e99fcd0926a0
        userCondition: null
handle: about
hasTitleField: true
icon: null
name: About
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
