color: null
fieldLayouts:
  2e7ac708-817a-45ee-a6f1-48ed25beb1eb:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-07T17:13:45+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: df921e9d-a80d-4a33-86e7-bd5dbf7cb56c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-07T17:16:12+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: aa544899-f81a-4428-bf55-3a28f6f66e7e # Accordion Item Type
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 49b0d3d5-7815-453f-a4d6-5637a3c5da76
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-07T17:16:12+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 4a1c5af6-a7e9-4954-b7c6-a7aa41efbc40
            userCondition: null
          -
            dateAdded: '2025-05-07T17:17:43+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: aa544899-f81a-4428-bf55-3a28f6f66e7e # Accordion Item Type
                  layoutElementUid: 49b0d3d5-7815-453f-a4d6-5637a3c5da76
                  operator: in
                  uid: bae16183-9e33-4e5b-8c7a-0dec88983135
                  values:
                    - subAccordion
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 72ea8454-0e94-4a5e-af51-450122fc59e9 # Sub-accordion Items
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d52d3809-2d5e-4754-9acd-d6123af714ab
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4244d603-0cd9-43a1-90c3-148d7a01bb60
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-09T19:01:33+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6ed3184f-7a68-4bb3-b991-e86a3a3fac25 # Section ID
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 362d47dc-9117-43d2-90d9-c953fcc24981
            userCondition: null
            warning: null
            width: 100
        name: Config
        uid: f8e26416-92fe-46cc-8a30-498068e9bef7
        userCondition: null
handle: accordionItem
hasTitleField: true
icon: null
name: 'Accordion Item'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
