color: null
fieldLayouts:
  f45882d9-88a8-4326-aa77-882a67647757:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-06T21:24:46+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b23562c7-8252-4a24-b6c7-d2b2d07f8ce2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-06T21:26:06+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c975e4b8-725b-40cf-8289-e0758ed7d08a # Body
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5e69c79d-5516-429b-a433-5c8418dd9996
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-06T21:26:06+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e3c44a40-6b4f-492f-945f-b71ab515f2cc # Links
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0fd0d62e-1376-4250-99e3-d9ecc0810eeb
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: fb7c5ca5-8d1d-46fe-9be3-05d088612527
        userCondition: null
handle: advantage
hasTitleField: true
icon: null
name: Advantage
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
