color: null
fieldLayouts:
  25229992-80c3-4214-a0bf-4abd3455a7ff:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-07T21:19:28+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 277c4b06-8b09-420c-a9ad-db7771f48862 # List
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 227cf929-f1b9-400a-8f11-7f4434758868
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-07T21:19:28+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: aac3e44d-b810-42c7-be08-8c6a19a3340a # Media Item
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 68a67122-2074-42e9-ab79-eb8ab5a218c3
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-09T22:23:40+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f81c03e1-8c27-46c6-a5bc-f77c57567109
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-07T21:19:28+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e3c44a40-6b4f-492f-945f-b71ab515f2cc # Links
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d306399b-aa9a-42d6-8552-72263b68a9da
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a15f8368-466e-4951-b232-c5698e63288b
        userCondition: null
handle: conclusion
hasTitleField: true
icon: null
name: Conclusion
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
