color: null
fieldLayouts:
  75f2b5e1-f87a-4d4a-a563-12d862a477f2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-05T18:50:26+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 97ae6f3e-6ff8-4f2f-9ac9-3d99740a2b97
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-05T18:52:26+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c975e4b8-725b-40cf-8289-e0758ed7d08a # Body
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b8e5c17c-feeb-458d-acff-d45a72c141f9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-05T18:52:26+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e3c44a40-6b4f-492f-945f-b71ab515f2cc # Links
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e81825ca-73e6-47a7-85b3-26dbe8f6a54b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-05T18:52:26+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: aac3e44d-b810-42c7-be08-8c6a19a3340a # Media Item
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 550582e9-f2ef-4adc-8649-c81dbff36b74
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5715a369-22ab-4c4c-aea4-d96efe0cbf70
        userCondition: null
handle: hero
hasTitleField: true
icon: null
name: Hero
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
