color: null
fieldLayouts:
  b2fc13cb-09ac-4f43-a57c-79f797be2bd4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-07T23:23:08+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8ac7280b-17df-4df4-979c-86478750ea3d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-07T23:26:03+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c975e4b8-725b-40cf-8289-e0758ed7d08a # Body
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0b181e7e-005d-4796-a230-ac87a9d7ba6e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-13T17:31:18+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e239bfbf-aadc-4869-b083-1b89af5a294e # Positioning CSS
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8978bf46-2108-46d4-a4f8-caa29d20c5b4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9ba7d54b-e99e-4593-9768-147147a49b24
        userCondition: null
handle: imageTooltip
hasTitleField: true
icon: null
name: 'Image Tooltip'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
