color: null
fieldLayouts:
  922b6fb6-0594-4601-9b51-3f9cd8b30f15:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-19T20:13:24+00:00'
            elementCondition: null
            fieldUid: eae22444-22c9-4f11-a5d8-075056c0c45c # Media Items
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f23c49c3-c85a-4c4b-a26d-beaf24942388
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7722f601-b62a-4b53-97cc-58693d32d83c
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-04T20:30:09+00:00'
            elementCondition: null
            fieldUid: 6ed3184f-7a68-4bb3-b991-e86a3a3fac25 # Section ID
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2ff0d3ab-0ff4-42cf-aaf0-b1f0184d7f9e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-04T20:30:09+00:00'
            elementCondition: null
            fieldUid: 14939870-1802-4300-9fc9-a7a8ff00504e
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b8a22a04-651a-42d9-9f54-4c92ebc79719
            userCondition: null
            warning: null
            width: 100
        name: Config
        uid: 4291242e-ec2f-4b7e-a805-a2bf422ce599
        userCondition: null
handle: mediaItems
hasTitleField: false
icon: ''
name: 'Media Items'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
