color: null
fieldLayouts:
  8a713444-db4e-445a-bbe2-e24701f612b0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-07T16:06:32+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: db9f0ef0-2ae0-4625-bb55-ff070d64492d # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b0109705-5a2d-4447-92db-3238a21df476
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-05-07T16:06:32+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 94674bfa-687b-4684-bde9-d87a991f7e19 # Scale
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8e364e96-6e47-4903-a6ce-5cd0b403e504
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 46d2c2d7-1a26-425a-ab94-a0ab1ed0515e
        userCondition: null
handle: partnerLogo
hasTitleField: false
icon: null
name: 'Partner Logo'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
