color: null
fieldLayouts:
  ed1498f0-9efb-4089-9fb4-df6f69f390f7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-06T23:50:16+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8928ac74-b577-4ef2-b446-c9104ad307e1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-07T16:06:36+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e604059d-87e0-4aef-84fe-410cc97c3b48 # Partner Logos
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 32d8eeee-2d3e-49fd-8f30-15c95081c978
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4c62ce4e-fe1c-4cf3-9634-933413d959d4
        userCondition: null
handle: partners
hasTitleField: true
icon: null
name: Partners
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
