color: null
fieldLayouts:
  97cd2112-82f0-4393-95f4-f0d40e72dbf3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-12T00:56:51+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: fc21189e-909c-4cb8-9b20-d93d408b81da
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-12T00:58:32+00:00'
            elementCondition: null
            fieldUid: 5c56c6be-53a9-4a60-b2f7-85bfcc1c171f # Headline Style
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b67081f7-722f-414c-8f89-48da8ea5c6fb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-12T00:58:32+00:00'
            elementCondition: null
            fieldUid: c0795bfe-23f8-4401-b211-56060b719096
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0b8ac072-42f2-4963-8309-092066a0d962
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c9b3d69e-6aa9-4672-be46-317e024247c3
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-12T00:58:32+00:00'
            elementCondition: null
            fieldUid: 6ed3184f-7a68-4bb3-b991-e86a3a3fac25 # Section ID
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8b42ca8a-2a0c-4b13-a821-ee779ab00a3c
            userCondition: null
            warning: null
            width: 100
        name: Config
        uid: 622208f4-0c5e-4d89-8bdb-9550213afa35
        userCondition: null
handle: postStats
hasTitleField: true
icon: ''
name: 'Post Stats'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
