color: null
fieldLayouts:
  6eb5d3f1-95ee-4f8b-85a8-765847a819da:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-12T20:47:29+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 75fada58-4012-4038-a8c9-b10bf18ff548
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-12T20:50:53+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 58c0aa4f-e0d5-466a-965e-40b3f23607d5
            userCondition: null
          -
            dateAdded: '2024-12-04T18:20:17+00:00'
            elementCondition: null
            fieldUid: 6a3cb58c-9a14-477f-b888-501f4877d1cd # Featured Post
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 89288f79-ceb4-45ce-b5a7-2ae141b38432
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ad417f4e-8822-4829-8073-025225199761
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-12T20:50:53+00:00'
            elementCondition: null
            fieldUid: 6ed3184f-7a68-4bb3-b991-e86a3a3fac25 # Section ID
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b2e9a059-ff28-46e8-a6b0-f230677d34ed
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-04T18:20:17+00:00'
            elementCondition: null
            fieldUid: 14939870-1802-4300-9fc9-a7a8ff00504e
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b76257e1-a527-48aa-93dc-e1627a2760fe
            userCondition: null
            warning: null
            width: 100
        name: Config
        uid: 6bd644ee-6819-44a0-a125-1db897a926bf
        userCondition: null
handle: postIndex
hasTitleField: true
icon: ''
name: 'Post Index'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
