color: null
fieldLayouts:
  880fe203-f4e9-43f9-8517-185771c21348:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-04T00:23:36+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 917e5dab-5758-4290-908b-b8a79d15c692
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-09T18:17:41+00:00'
            elementCondition: null
            fieldUid: 979cd403-57a5-4d2e-8037-3331eedcad60 # Posts
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5ed0ced2-dacd-4b5e-973f-ab2c0d5f029b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 29473323-8ae2-42c9-8e1d-ebed3c714aeb
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-04T00:26:32+00:00'
            elementCondition: null
            fieldUid: 6ed3184f-7a68-4bb3-b991-e86a3a3fac25 # Section ID
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3eca9afa-a39b-4655-be87-77d26969a9db
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-04T00:26:32+00:00'
            elementCondition: null
            fieldUid: 14939870-1802-4300-9fc9-a7a8ff00504e
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0d3b8865-4962-42d1-94bf-cacda050117a
            userCondition: null
            warning: null
            width: 100
        name: Config
        uid: 8fb21863-1b6c-4f5e-a36b-4a41885ecb2e
        userCondition: null
handle: postPreviews
hasTitleField: true
icon: ''
name: 'Post Previews'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
