color: null
fieldLayouts:
  705ee912-2ac8-49ae-b723-82c21c07c129:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-12T17:00:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: aac3e44d-b810-42c7-be08-8c6a19a3340a # Media Item
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7a1bfc66-4edb-433c-ba69-e7716e6d0e62
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-12T17:09:39+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: e0f57f2c-d12e-4410-b271-1a24926e77cc
            userCondition: null
          -
            dateAdded: '2024-12-12T17:07:11+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c610afb3-1efa-4b91-a5fd-33934271b95f # Caption
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ee0dead9-9e7b-4d6a-abfa-b105daa3cf80
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d40b0091-4f5e-4b3a-a761-74e7bfa47dce
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-12T17:12:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6ed3184f-7a68-4bb3-b991-e86a3a3fac25 # Section ID
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1b01e0c9-7787-4b32-ac52-8d3a62055fdd
            userCondition: null
            warning: null
            width: 100
        name: Config
        uid: 4b1c518e-65d2-4f62-b8d5-0575788fa1ac
        userCondition: null
handle: postMedia
hasTitleField: false
icon: null
name: 'Post Media'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
