color: null
fieldLayouts:
  08a87d78-2490-45b2-8897-f158136fa499:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-11T19:03:06+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ef3fb470-e012-44bb-a32d-ef9947428f0e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-13T18:52:46+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0fe347cf-5e7b-4446-a9e1-359f64551463 # Text
            handle: authorName
            includeInCards: false
            instructions: null
            label: 'Author Name'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 00ddf91b-8666-4edb-8c4e-3441e48152b5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-13T18:52:46+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0fe347cf-5e7b-4446-a9e1-359f64551463 # Text
            handle: readTime
            includeInCards: false
            instructions: null
            label: 'Read Time'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 21fe9ecd-804a-4020-8a43-7e9ef3cbf713
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-12T22:09:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: db9f0ef0-2ae0-4625-bb55-ff070d64492d # Image
            handle: null
            includeInCards: false
            instructions: null
            label: 'Preview Image'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3dfeee8f-ee44-4a6e-a1db-088e67fcf666
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-09-11T19:05:26+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f1d51b4b-7d86-41ba-b54a-b81f85ea651d # Post Categories
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 680f7b16-8837-4657-8845-fe4d72398981
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-09-12T22:09:31+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 0b2d7b2d-30a3-478c-89f2-f9d2962ea218
            userCondition: null
          -
            dateAdded: '2024-09-11T23:21:17+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 081b2fb0-369f-483e-a571-631f02ef49e5 # Post Sections
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e5a8a18a-0167-4112-a3d8-ea260d1739b1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-12T19:07:01+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 14df0ef7-0338-4d16-a1b4-542192e945de
            userCondition: null
          -
            dateAdded: '2024-12-12T19:07:01+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 979cd403-57a5-4d2e-8037-3331eedcad60 # Posts
            handle: relatedPosts
            includeInCards: false
            instructions: 'If no related posts are chosen, posts from the same category will automatically be used.'
            label: 'Related Posts'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a3f7fa0d-8c57-4231-b82b-dc50713d3b93
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8625d288-d956-4471-8937-08563ed315b0
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-11T19:09:23+00:00'
            dismissible: false
            elementCondition: null
            style: tip
            tip: 'These meta fields will override their global counterparts in the Globals > Meta section on a per-post basis. In the case of "Meta Title", if not set, the Post''s title field will be used.'
            type: craft\fieldlayoutelements\Tip
            uid: 16803d87-aada-4977-9077-d435a4f15882
            userCondition: null
          -
            dateAdded: '2024-09-11T19:09:23+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7bedc8bb-4bc6-422c-b318-9d01c50df39f # Meta Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 449a31a4-c286-4ed4-a15b-74450c2b92dc
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-11T19:09:23+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b722d671-d96f-4d4b-afa3-f3c1c446e20e # Meta Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 77330ce0-62f9-4496-89c2-47144dd74a6a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-11T19:09:23+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 307f8307-f006-49b9-aa8b-900ddb2f0767 # Meta Keywords
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d4bd3317-0436-4203-b58b-27ac0de9352f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-11T19:09:23+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5eff4a3a-4d04-402d-b07e-0ee136a5eacc # Meta Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0c333fba-674c-404a-9b6f-cc7a74f91e15
            userCondition: null
            warning: null
            width: 100
        name: Meta
        uid: 17ca9ba6-d58f-4169-b459-33259b94aab7
        userCondition: null
handle: post
hasTitleField: true
icon: null
name: Post
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
