color: null
fieldLayouts:
  a460d0fe-5558-4750-afd3-d3ef05e0b948:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-01T15:51:12+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b19a7d05-380d-42dd-b022-10ad05d0aacd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-01T15:51:12+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: db9f0ef0-2ae0-4625-bb55-ff070d64492d # Image
            handle: productNameImage
            includeInCards: false
            instructions: null
            label: 'Product Name Image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: efed6c9a-fa46-434b-ade9-855152d3653e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-01T15:41:23+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c975e4b8-725b-40cf-8289-e0758ed7d08a # Body
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 325b97b1-06df-4fa9-bb15-20afded66249
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-01T15:53:59+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: db9f0ef0-2ae0-4625-bb55-ff070d64492d # Image
            handle: satelliteImage
            includeInCards: false
            instructions: null
            label: 'Satellite Image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b9fe9f8a-108b-44e3-a487-bd666eea8fef
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: fe3ea129-c13d-451a-8b62-a7e2f38b2e8c
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-01T15:41:23+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6ed3184f-7a68-4bb3-b991-e86a3a3fac25 # Section ID
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d6a47668-ebbc-44eb-bbe5-c13bf7283332
            userCondition: null
            warning: null
            width: 100
        name: Config
        uid: 1caedfeb-3ba5-4116-a143-b8ec879dc4ea
        userCondition: null
handle: satelliteIntro
hasTitleField: true
icon: null
name: 'Satellite Intro'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
