altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  8d6042c9-5a93-4489-9ebc-a43cef81fd1f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-15T17:46:56+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 2f710aea-bd2a-4dde-b8fa-2f57933f1e3e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 60159588-6bae-4568-b09b-40c8c6b48461
        userCondition: null
fs: servd
handle: servd
name: Servd
sortOrder: 6
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
