defaultPlacement: end
fieldLayouts:
  146fb021-2743-4d3d-bb31-45eab6c56ce6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-11T19:03:32+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 4ccfbdfa-9b18-47c6-8db1-dab6d0f9be6f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: cc2ea80f-903c-424d-b335-3da4b457d093
        userCondition: null
handle: postCategories
name: 'Post Categories'
siteSettings:
  04df0f5f-b9d5-4dda-b9a8-bcccda506022: # Pathstream
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 1
  uid: 58692403-154b-4399-a644-7c6c0178b92f
