fieldLayouts:
  b1de7ef6-bcac-4cbb-a130-3023076c16f2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-04T00:16:15+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 9df10036-c5af-43ef-ae05-c471b70d0bbd
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: bc66e47c-f961-403b-afe0-0d5057b21c8b
        userCondition: null
handle: postTags
name: 'Post Tags'
