description: null
handle: editor
name: Editor
permissions:
  - accesscp
  - accesscpwhensystemisoff
  - accesssitewhensystemisoff
  - administrateusers
  - 'assignusergroup:a9ecbb3a-4ffa-4f23-b5e6-052187ed4bd6' # Editor
  - assignuserpermissions
  - 'createentries:a1e0354d-b430-47a5-858b-c83ebc9730f8'
  - 'createentries:c1f9043c-a9fe-4828-8b12-e36d12842d7e' # Page
  - 'createentries:e20465eb-96b7-4f76-9f57-e12f30c984cf' # Post
  - 'createfolders:86f72bf0-5926-43ac-b10f-632e9112b9bd'
  - 'deleteassets:86f72bf0-5926-43ac-b10f-632e9112b9bd'
  - 'deletecategories:4fdb97ac-06c8-4dc0-abf3-5b73cf2853f7' # Post Categories
  - 'deleteentries:a1e0354d-b430-47a5-858b-c83ebc9730f8'
  - 'deleteentries:c1f9043c-a9fe-4828-8b12-e36d12842d7e' # Page
  - 'deleteentries:e20465eb-96b7-4f76-9f57-e12f30c984cf' # Post
  - 'deletepeerassets:86f72bf0-5926-43ac-b10f-632e9112b9bd'
  - 'deletepeercategorydrafts:4fdb97ac-06c8-4dc0-abf3-5b73cf2853f7' # Post Categories
  - 'deletepeerentries:a1e0354d-b430-47a5-858b-c83ebc9730f8'
  - 'deletepeerentries:c1f9043c-a9fe-4828-8b12-e36d12842d7e' # Page
  - 'deletepeerentries:e20465eb-96b7-4f76-9f57-e12f30c984cf' # Post
  - 'deletepeerentrydrafts:a1e0354d-b430-47a5-858b-c83ebc9730f8'
  - 'deletepeerentrydrafts:c1f9043c-a9fe-4828-8b12-e36d12842d7e' # Page
  - 'deletepeerentrydrafts:e20465eb-96b7-4f76-9f57-e12f30c984cf' # Post
  - deleteusers
  - 'editglobalset:2e71983e-2107-47e6-a837-6dc4cb005f67' # Footer
  - 'editglobalset:6d8e7dbb-e381-432a-a557-670cf1e07636' # Scripts
  - 'editglobalset:aec5b961-4566-4b50-aea4-e12f93051f11' # Meta
  - 'editglobalset:ddcb06fd-e265-4e30-aec3-2cc4d8c791f5' # Header
  - 'editimages:86f72bf0-5926-43ac-b10f-632e9112b9bd'
  - 'editpeerimages:86f72bf0-5926-43ac-b10f-632e9112b9bd'
  - editusers
  - impersonateusers
  - moderateusers
  - registerusers
  - 'replacefiles:86f72bf0-5926-43ac-b10f-632e9112b9bd'
  - 'replacepeerfiles:86f72bf0-5926-43ac-b10f-632e9112b9bd'
  - 'saveassets:86f72bf0-5926-43ac-b10f-632e9112b9bd'
  - 'savecategories:4fdb97ac-06c8-4dc0-abf3-5b73cf2853f7' # Post Categories
  - 'saveentries:a1e0354d-b430-47a5-858b-c83ebc9730f8'
  - 'saveentries:c1f9043c-a9fe-4828-8b12-e36d12842d7e' # Page
  - 'saveentries:e20465eb-96b7-4f76-9f57-e12f30c984cf' # Post
  - 'savepeerassets:86f72bf0-5926-43ac-b10f-632e9112b9bd'
  - 'savepeercategorydrafts:4fdb97ac-06c8-4dc0-abf3-5b73cf2853f7' # Post Categories
  - 'savepeerentries:a1e0354d-b430-47a5-858b-c83ebc9730f8'
  - 'savepeerentries:c1f9043c-a9fe-4828-8b12-e36d12842d7e' # Page
  - 'savepeerentries:e20465eb-96b7-4f76-9f57-e12f30c984cf' # Post
  - 'savepeerentrydrafts:a1e0354d-b430-47a5-858b-c83ebc9730f8'
  - 'savepeerentrydrafts:c1f9043c-a9fe-4828-8b12-e36d12842d7e' # Page
  - 'savepeerentrydrafts:e20465eb-96b7-4f76-9f57-e12f30c984cf' # Post
  - 'sprout-module-redirects:accessmodule'
  - 'sprout-module-redirects:editredirects'
  - 'sprout-module-sitemaps:accessmodule'
  - 'sprout-module-sitemaps:editsitemaps'
  - 'utility:clear-caches'
  - 'utility:db-backup'
  - 'utility:find-replace'
  - 'viewassets:86f72bf0-5926-43ac-b10f-632e9112b9bd'
  - 'viewcategories:4fdb97ac-06c8-4dc0-abf3-5b73cf2853f7' # Post Categories
  - 'viewentries:a1e0354d-b430-47a5-858b-c83ebc9730f8'
  - 'viewentries:c1f9043c-a9fe-4828-8b12-e36d12842d7e' # Page
  - 'viewentries:e20465eb-96b7-4f76-9f57-e12f30c984cf' # Post
  - 'viewpeerassets:86f72bf0-5926-43ac-b10f-632e9112b9bd'
  - 'viewpeercategorydrafts:4fdb97ac-06c8-4dc0-abf3-5b73cf2853f7' # Post Categories
  - 'viewpeerentries:a1e0354d-b430-47a5-858b-c83ebc9730f8'
  - 'viewpeerentries:c1f9043c-a9fe-4828-8b12-e36d12842d7e' # Page
  - 'viewpeerentries:e20465eb-96b7-4f76-9f57-e12f30c984cf' # Post
  - 'viewpeerentrydrafts:a1e0354d-b430-47a5-858b-c83ebc9730f8'
  - 'viewpeerentrydrafts:c1f9043c-a9fe-4828-8b12-e36d12842d7e' # Page
  - 'viewpeerentrydrafts:e20465eb-96b7-4f76-9f57-e12f30c984cf' # Post
  - viewusers
